name: cars
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_phone_auth_handler: ^1.0.8
  firebase_auth: ^4.7.2
  flutter_bloc: ^8.1.3
  mask_text_input_formatter: ^2.5.0
  get: ^4.6.5
  yandex_mapkit: ^3.3.3
  geolocator: ^9.0.2
  hive: ^2.2.3
  solid_bottom_sheet: ^0.1.10
  bottom_sheet_bar: ^2.3.9
  yandex_geocoder: ^2.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.0
  flutter_svg: ^2.0.7
  wheel_chooser: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.1.13
  bottom_sheet: ^3.1.2
  bottom_bar_with_sheet: ^2.4.0
  expandable_bottom_sheet: ^1.1.1+1
  drag_and_drop_lists: ^0.3.3
  cloud_firestore: ^4.8.4
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.0
  dio_cookie_manager: ^3.1.0+1
  cookie_jar: ^4.0.8
  flutter_azimuth: ^1.0.1
  flutter_localization: ^0.1.13
  ext_video_player: ^0.1.2
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
  firebase_messaging: ^14.6.7
  flutter_callkit_incoming: ^2.0.3
  awesome_notifications: ^0.8.2
  flutter_local_notifications: ^17.0.0
  onesignal_flutter: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - asstes/route.png
    - asstes/point2.png
    - asstes/finish.png
    - asstes/point.png
    - asstes/point_black.png
    - asstes/telegram.svg
    - asstes/car.png
    - asstes/logo.svg
    - asstes/camry.png
    - asstes/wheel.png
    - asstes/zag.png
    - asstes/abs.png
    - asstes/cam.png
    - asstes/webcam.png
    - asstes/webcam3.png
    - asstes/cam3.png
    - asstes/cam4.png
    - asstes/cam5.png
    - asstes/cam6.png
    - asstes/webcam2.png
    - asstes/cam7.png
    - asstes/point_1.png
    - asstes/map.png
