// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJnowKfuPB391-iycDGe-OuXbbo3J--I',
    appId: '1:591099938047:android:7fe6d45f0ea6a6466ff8ca',
    messagingSenderId: '591099938047',
    projectId: 'baitekapp',
    storageBucket: 'baitekapp.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJrNYAo1ElnYiNAI_Pot0yPrXVvKfnHA',
    appId: '1:591099938047:web:1e4cc66a9648915a6ff8ca',
    messagingSenderId: '591099938047',
    projectId: 'baitekapp',
    authDomain: 'baitekapp.firebaseapp.com',
    storageBucket: 'baitekapp.appspot.com',
    measurementId: 'G-56D8WNFZYM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCawX1Lw_AZhke6l-8yHVUY8KeNoZEPY0c',
    appId: '1:591099938047:ios:71f284efd9349f406ff8ca',
    messagingSenderId: '591099938047',
    projectId: 'baitekapp',
    storageBucket: 'baitekapp.appspot.com',
    iosBundleId: 'com.example.taxifianal',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCawX1Lw_AZhke6l-8yHVUY8KeNoZEPY0c',
    appId: '1:591099938047:ios:71f284efd9349f406ff8ca',
    messagingSenderId: '591099938047',
    projectId: 'baitekapp',
    storageBucket: 'baitekapp.appspot.com',
    iosBundleId: 'com.example.taxifianal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrJrNYAo1ElnYiNAI_Pot0yPrXVvKfnHA',
    appId: '1:591099938047:web:59b0f555809f9d7e6ff8ca',
    messagingSenderId: '591099938047',
    projectId: 'baitekapp',
    authDomain: 'baitekapp.firebaseapp.com',
    storageBucket: 'baitekapp.appspot.com',
    measurementId: 'G-6HFXNH362W',
  );

}